//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arrival
    {
        public int IdComing { get; set; }
        public Nullable<int> IdEmployee { get; set; }
        public Nullable<System.DateTime> ArrivalTime { get; set; }
        public Nullable<int> idFine { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual Fine Fine { get; set; }
    }
}
